### ISSUE TITLE
显示有密钥且正在使用,页面却显示没有密钥???什么鬼

### ISSUE THREAD

**Issue by yangqihang521** [2375452377/note#25]
![image](https://user-images.githubusercontent.com/53083611/69632788-52dd7d80-108a-11ea-8c6b-2db5e13224ff.png)

**Comment by terrluo** [comment]
你应该是在别的 github 账号上使用过这个密钥了

**Comment by yangqihang521** [comment]
> github



> 你应该是在别的github帐户上使用过这个密钥了

是此账户 的别的项目上
